version: '2'
volumes:
  whisper:
    driver: local
services:
  carbon:
    build: ./carbon-whisper
    image: bkmeneguello/carbon-whisper
    volumes:
    - whisper:/opt/graphite/storage/whisper
    - ./carbon-whisper/conf:/opt/graphite/conf:ro
    ports:
    - "2003-2004:2003-2004"
  graphite:
    build: ./graphite-api
    image: bkmeneguello/graphite-api
    volumes:
    - whisper:/opt/graphite/storage/whisper
    - ./graphite-api/graphite-api.yaml:/etc/graphite-api.yaml:ro
    links:
    - carbon
  grafana:
    build: ./grafana
    image: bkmeneguello/grafana
    links:
    - graphite
    ports:
    - "3000:3000"
  statsd:
    build: ./statsd
    image: bkmeneguello/statsd
    volumes:
    - ./statsd/config.js:/statsd/config.js:ro
    links:
    - carbon
    ports:
    - "8125:8125/udp"
  netdata:
    build: ./netdata
    image: bkmeneguello/netdata
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - ./netdata/netdata.conf:/etc/netdata/netdata.conf
    links:
    - carbon
    ports:
    - "19999:19999"
    cap_add:
    - SYS_PTRACE
